# Generated by Django 5.0.3 on 2024-05-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_book_genre_alter_book_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookshelf",
            name="book",
            field=models.ManyToManyField(blank=True, to="app.book"),
        ),
        migrations.AlterField(
            model_name="bookshelf",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
