# Generated by Django 5.0.3 on 2024-05-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_bookshelf_book_alter_bookshelf_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
