# Generated by Django 5.0.3 on 2024-05-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_book_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
