# Generated by Django 5.0.3 on 2024-05-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_book_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Horror", "Horror"),
                    ("Fantasy", "Fantasy"),
                    ("Sci-Fi", "Sci-Fi"),
                    ("Thriller", "Thriller"),
                    ("Mystery", "Mystery"),
                ],
                max_length=200,
            ),
        ),
    ]
