# Generated by Django 5.0.3 on 2024-05-13 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_progress"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Progress",
        ),
    ]
