# Generated by Django 5.0.3 on 2024-05-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_delete_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookshelf",
            name="book",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="app.book"
            ),
        ),
    ]
