# Generated by Django 5.0.3 on 2024-05-14 02:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_bookshelf_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookshelf",
            old_name="book",
            new_name="books",
        ),
    ]
