# Generated by Django 5.0.3 on 2024-05-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_alter_comment_post_review_comment_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="profile",
            field=models.ManyToManyField(blank=True, null=True, to="app.profile"),
        ),
    ]
