# Generated by Django 5.0.3 on 2024-05-16 23:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_alter_book_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="rating",
        ),
    ]
