# Generated by Django 5.0.3 on 2024-05-24 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_remove_bookshelf_profile_bookshelf_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookshelf",
            name="description",
        ),
        migrations.RemoveField(
            model_name="bookshelf",
            name="profile",
        ),
        migrations.AddField(
            model_name="bookshelf",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="app.profile",
            ),
        ),
    ]
