# Generated by Django 5.0.3 on 2024-05-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0021_remove_bookshelf_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="book",
            name="genre",
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(to="app.genre"),
        ),
    ]
