# Generated by Django 5.0.3 on 2024-05-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_genre_remove_book_genre_book_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("-", ""),
                    ("Read", "Read"),
                    ("Currently Reading", "Currently Reading"),
                    ("Want to Read", "Want to Read"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
