# Generated by Django 5.0.3 on 2024-05-25 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0023_book_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="book",
            name="status",
        ),
    ]
